<?php

namespace Jet_Form_Builder\Actions\Methods\Update_User;

use Jet_Form_Builder\Actions\Methods\Abstract_Modifier;
use Jet_Form_Builder\Exceptions\Action_Exception;

class User_Modifier extends Abstract_Modifier {

	/** @var \WP_User */
	public $updated_user;

	/** @var string */
	private $user_role;

	public function get_actions() {
		return apply_filters(
			'jet-form-builder/user-modifier/object-actions',
			array(
				'update' => array(
					'action' => array( $this, 'update_user' ),
				),
			)
		);
	}

	public function get_action() {
		return 'update';
	}

	/**
	 * @throws Action_Exception
	 */
	public function update_user() {
		$response = wp_update_user( $this->source_arr );

		if ( is_wp_error( $response ) ) {
			throw ( new Action_Exception(
				$response->get_error_message(),
				$response->get_error_data()
			)
			)->dynamic_error();
		}

		if ( ! empty( $this->user_role ) ) {
			$this->updated_user->set_role( $this->user_role );
		}
	}

	public function set_user_role( $role ) {
		if ( ! empty( $role ) && 'administrator' !== $role ) {
			$this->user_role = $role;
		}

		return $this;
	}

	/**
	 * @throws Action_Exception
	 */
	public function run() {
		if ( ! is_user_logged_in() ) {
			// Only logged in users can edit other users
			throw new Action_Exception( 'internal_error' );
		}

		parent::run(); // TODO: Change the autogenerated stub
	}
}
