#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

while read local_ref local_sha remote_ref remote_sha; do
    # Extracting the branch name
    branch_name=$(echo "$local_ref" | cut -d '/' -f 3-)

    # Check if the branch name matches any of the specified patterns
    # shellcheck disable=SC2039
    if ! [[ "$branch_name" =~ ^(main|(release/[0-9]+\.[0-9]+\.[0-9]+)|(issue/[0-9]+)|(suggestion/[0-9]+)|(feature/[a-z0-9\-]+)|(dev/[a-z0-9\-]+))$ ]]; then
        echo "Error: Branch name \"$branch_name\" is not allowed."
        exit 1
    fi
done
