name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send release info to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          CLEAN_CHANGELOG=$(echo "$RELEASE_BODY" | tr "'\"" '`')

          if [ ${#CLEAN_CHANGELOG} -gt 3000 ]; then
            CLEAN_CHANGELOG="${CLEAN_CHANGELOG:0:3000}..."
          fi

          VERSION="${{ github.event.release.tag_name }}"
          PLUGIN_NAME="JetFormBuilder"
          TITLE="🚀 $PLUGIN_NAME $VERSION"

          JSON=$(jq -n \
            --arg title "$TITLE" \
            --arg desc "$CLEAN_CHANGELOG" \
            '{
              embeds: [
                {
                  title: $title,
                  description: ($desc + "\n\n**https://crocoblock.com/changelog/**"),
                  color: 5814783
                }
              ]
            }')

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$JSON" \
               "$DISCORD_WEBHOOK_URL"
