name: PHP CodeSniffer Linter

on:
    push:
        branches:
            - 3.1.0
    pull_request:
        branches:
            - 3.1.0
    # Allow manually triggering the workflow.
    workflow_dispatch:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    phpcs:
        name: WPCS
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: WPCS check
                uses: 10up/wpcs-action@stable
                with:
                    standard: './phpcs.xml'
                    use_local_config: true
                    extra_args: '--report-json=./phpcs-report.json'

            -   name: Update summary
                run: |
                    npx github:10up/phpcs-json-to-md --path ./phpcs-report.json --output ./phpcs-report.md
                    cat phpcs-report.md >> $GITHUB_STEP_SUMMARY
                if: ${{ failure() }}